name: gh pr checks
description: Wait for PR checks via GitHub CLI
inputs:
  token:
    description: GitHub token for gh
    required: true
  pr_number:
    description: Pull request number
    required: true
runs:
  using: composite
  steps:
    - name: Wait for required checks
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        PR: ${{ inputs.pr_number }}
      run: |
        set -euo pipefail
        gh pr checks "$PR" --watch --fail-fast
