# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Setup Rust toolchain from rust-toolchain.toml
description: Install rustup and the toolchain specified in rust-toolchain.toml (pure shell, retry-safe)

inputs:
  toolchain-file:
    description: Path to rust-toolchain.toml
    required: false
    default: rust-toolchain.toml
  extra-components:
    description: Extra components to install (space-separated), for example "rustfmt clippy"
    required: false
    default: ""
  profile:
    description: Rustup profile to install
    required: false
    default: minimal

runs:
  using: composite
  steps:
    - name: Install rustup (retry-safe)
      shell: bash
      env:
        PROFILE: ${{ inputs.profile }}
      run: |
        set -euo pipefail

        curl -fsSL \
          --retry 12 \
          --retry-delay 2 \
          --retry-all-errors \
          --connect-timeout 15 \
          --max-time 600 \
          https://sh.rustup.rs -o /tmp/rustup.sh

        sh /tmp/rustup.sh -y --profile "${PROFILE}" --default-toolchain none --no-modify-path
        rm -f /tmp/rustup.sh

        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
        source "$HOME/.cargo/env"

        echo "rustup installed:"
        rustup -V

    - name: Install toolchain from file
      shell: bash
      env:
        TOOLCHAIN_FILE: ${{ inputs.toolchain-file }}
        EXTRA_COMPONENTS: ${{ inputs.extra-components }}
        PROFILE: ${{ inputs.profile }}
      run: |
        set -euo pipefail

        if [ ! -f "$TOOLCHAIN_FILE" ]; then
          echo "Toolchain file not found: $TOOLCHAIN_FILE" >&2
          exit 1
        fi

        toolchain="$(grep -E '^[[:space:]]*channel[[:space:]]*=' "$TOOLCHAIN_FILE" | head -n1 | sed -E 's/^[[:space:]]*channel[[:space:]]*=[[:space:]]*"([^"]+)".*$/\1/')"
        if [ -z "${toolchain:-}" ]; then
          toolchain="nightly"
        fi

        rustup toolchain install "$toolchain" --profile "${PROFILE}"
        rustup default "$toolchain"

        if [ -n "${EXTRA_COMPONENTS:-}" ]; then
          rustup component add ${EXTRA_COMPONENTS} --toolchain "$toolchain"
        fi

        rustc -Vv
        cargo -V
        rustup show active-toolchain
