# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: gh pr review approve
description: Approve a pull request via GitHub CLI
inputs:
  token:
    description: GitHub token for gh
    required: true
  pr_number:
    description: Pull request number
    required: true
runs:
  using: composite
  steps:
    - name: Approve PR
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        PR: ${{ inputs.pr_number }}
      run: |
        set -euo pipefail
        gh pr review "$PR" --approve
