name: Bump Cargo version
description: Bump Cargo.toml version, regenerate lockfile, compute tag
inputs:
  bump:
    description: Version bump kind (patch|minor|major)
    required: true
  package_name:
    description: Cargo package name
    required: true
outputs:
  version:
    description: Next version X.Y.Z
    value: ${{ steps.bump.outputs.version }}
  tag:
    description: Tag vX.Y.Z
    value: ${{ steps.bump.outputs.tag }}
runs:
  using: composite
  steps:
    - name: Bump version
      id: bump
      shell: bash
      env:
        BUMP: ${{ inputs.bump }}
        PACKAGE_NAME: ${{ inputs.package_name }}
      run: |
        set -euo pipefail

        git fetch --tags --force

        meta_file="$(mktemp)"
        cargo metadata --no-deps --format-version 1 > "$meta_file"

        current="$(jq -r --arg name "$PACKAGE_NAME" '.packages[] | select(.name == $name) | .version' "$meta_file")"
        if [ -z "$current" ] || [ "$current" = "null" ]; then
          echo "Failed to find package version in cargo metadata. package=$PACKAGE_NAME" >&2
          cat "$meta_file" >&2
          exit 1
        fi
        if ! echo "$current" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "Current version is not semver X.Y.Z: $current" >&2
          exit 1
        fi

        latest_tag="$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | head -n1 || true)"
        if [ -n "$latest_tag" ]; then
          latest="${latest_tag#v}"
        else
          latest="0.0.0"
        fi

        parse_semver() {
          local v="$1"
          IFS='.' read -r a b c <<<"$v"
          echo "${a:-0} ${b:-0} ${c:-0}"
        }

        semver_gt() {
          local ax ay az bx by bz
          read -r ax ay az <<<"$(parse_semver "$1")"
          read -r bx by bz <<<"$(parse_semver "$2")"
          if [ "$ax" -ne "$bx" ]; then [ "$ax" -gt "$bx" ]; return; fi
          if [ "$ay" -ne "$by" ]; then [ "$ay" -gt "$by" ]; return; fi
          [ "$az" -gt "$bz" ]
        }

        bump_semver() {
          local v="$1" kind="$2"
          local x y z
          read -r x y z <<<"$(parse_semver "$v")"
          case "$kind" in
            major) x=$((x+1)); y=0; z=0 ;;
            minor) y=$((y+1)); z=0 ;;
            patch) z=$((z+1)) ;;
            *) echo "Unexpected bump kind: $kind" >&2; exit 1 ;;
          esac
          echo "$x.$y.$z"
        }

        base="$latest"
        if semver_gt "$current" "$latest"; then
          base="$current"
        fi

        next="$(bump_semver "$base" "$BUMP")"
        tag="v$next"

        if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
          echo "Tag already exists locally after fetch: $tag" >&2
          exit 1
        fi

        tmp="$(mktemp)"
        awk -v newver="$next" '
          BEGIN{in_pkg=0;done=0}
          /^\[package\]$/ {in_pkg=1; print; next}
          /^\[[^]]+\]$/ {in_pkg=0; print; next}
          in_pkg && !done && $0 ~ /^[[:space:]]*version[[:space:]]*=/ {
            print "version = \"" newver "\""
            done=1
            next
          }
          {print}
          END{
            if(!done){
              print "version field not found in [package]" > "/dev/stderr"
              exit 2
            }
          }
        ' Cargo.toml > "$tmp"
        mv "$tmp" Cargo.toml

        cargo generate-lockfile

        if [ -z "$(git diff --name-only -- Cargo.toml)" ]; then
          echo "Version bump produced no Cargo.toml change for version=$next" >&2
          exit 1
        fi

        echo "version=$next" >> "$GITHUB_OUTPUT"
        echo "tag=$tag" >> "$GITHUB_OUTPUT"
