name: Commit version bump
description: Create release bump branch and commit Cargo.toml and Cargo.lock
inputs:
  tag:
    description: Tag name (vX.Y.Z)
    required: true
outputs:
  branch:
    description: Created branch name
    value: ${{ steps.commit.outputs.branch }}
runs:
  using: composite
  steps:
    - name: Create branch and commit
      id: commit
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
      run: |
        set -euo pipefail
        branch="release/bump-${TAG}"

        git switch -c "$branch"
        git add Cargo.toml Cargo.lock

        if git diff --cached --quiet; then
          echo "No changes to commit after version bump." >&2
          exit 1
        fi

        git commit -m "release: ${TAG}"
        echo "branch=$branch" >> "$GITHUB_OUTPUT"
