# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Configure git identity (bot)
description: Configure git user.name and user.email for CI commits
inputs:
  user_name:
    description: git user.name
    required: false
    default: github-actions[bot]
  user_email:
    description: git user.email
    required: false
    default: 41898282+github-actions[bot]@users.noreply.github.com
runs:
  using: composite
  steps:
    - name: Set git identity (local + global)
      shell: bash
      run: |
        set -euo pipefail

        # Global config is required because some actions (e.g. push-branch)
        # commit in a fresh temporary clone.
        git config --global user.name "${{ inputs.user_name }}"
        git config --global user.email "${{ inputs.user_email }}"

        # Local config keeps behavior consistent for the checked-out workspace.
        git config user.name "${{ inputs.user_name }}"
        git config user.email "${{ inputs.user_email }}"
