# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: push-branch
description: Push current HEAD to a remote branch (no local commits)

inputs:
  repo_url:
    description: Repository HTTPS URL. If empty, uses current repository.
    required: false
    default: ""
  token:
    description: GitHub token (PAT) with push permissions
    required: true
  branch:
    description: Branch name to push to
    required: true
  delete_existing:
    description: If true, delete remote branch before pushing
    required: false
    default: "false"
  force:
    description: If true, force push (uses --force-with-lease)
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Push HEAD to remote branch
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        BRANCH: ${{ inputs.branch }}
        REPO_URL_IN: ${{ inputs.repo_url }}
        DELETE_EXISTING: ${{ inputs.delete_existing }}
        FORCE: ${{ inputs.force }}
      run: |
        set -euo pipefail

        if [ -z "${REPO_URL_IN}" ]; then
          if [ -z "${GITHUB_REPOSITORY:-}" ]; then
            echo "repo_url is empty and GITHUB_REPOSITORY is not set" >&2
            exit 1
          fi
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
        else
          REPO_URL="${REPO_URL_IN}"
        fi

        if [[ "${REPO_URL}" != https://* ]]; then
          echo "repo_url must be https URL (got: ${REPO_URL})" >&2
          exit 1
        fi

        REMOTE_URL="${REPO_URL/https:\/\//https:\/\/x-access-token:${TOKEN}@}"

        git remote set-url origin "$REMOTE_URL"

        if [ "${DELETE_EXISTING}" = "true" ]; then
          git push origin ":refs/heads/${BRANCH}" || true
        fi

        if [ "${FORCE}" = "true" ]; then
          git push origin "HEAD:refs/heads/${BRANCH}" --force-with-lease
        else
          git push origin "HEAD:refs/heads/${BRANCH}"
        fi
