# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Push branch
description: Push current HEAD to origin branch using token with retry and cleanup
inputs:
  token:
    description: GitHub token (PAT)
    required: true
  branch:
    description: Destination branch
    required: true
  delete-existing:
    description: Delete existing remote branch before push (resolves conflicts)
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Pre-check - validate branch name
      shell: bash
      env:
        BRANCH: ${{ inputs.branch }}
      run: |
        set -euo pipefail
        if ! echo "$BRANCH" | grep -Eqx '[a-zA-Z0-9._/-]+'; then
          echo "ERROR: Invalid branch name: $BRANCH" >&2
          exit 1
        fi
        echo "[INFO] Validated branch name: $BRANCH"

    - name: Pre-check - verify HEAD is clean
      shell: bash
      run: |
        set -euo pipefail
        if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then
          echo "ERROR: Working directory has uncommitted changes" >&2
          git status --porcelain
          exit 1
        fi
        echo "[INFO] Working directory is clean"

    - name: Clean up existing branch (if requested)
      if: ${{ inputs.delete-existing == 'true' }}
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        BRANCH: ${{ inputs.branch }}
      run: |
        set -euo pipefail
        git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        echo "[INFO] Attempting to delete existing remote branch: $BRANCH"
        if git push origin --delete "$BRANCH" 2>/dev/null; then
          echo "[INFO] Successfully deleted remote branch"
        else
          echo "[INFO] Remote branch did not exist, continuing"
        fi

    - name: Push branch with retry
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        BRANCH: ${{ inputs.branch }}
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
      run: |
        set -euo pipefail

        MAX_RETRIES=3
        RETRY_DELAY=2
        attempt=0

        git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git remote -v

        while [ "$attempt" -lt "$MAX_RETRIES" ]; do
          attempt=$((attempt + 1))
          echo "[INFO] Push attempt $attempt/$MAX_RETRIES: git push origin HEAD:$BRANCH"

          if git push origin "HEAD:${BRANCH}" --no-verify; then
            echo "[INFO] Successfully pushed $BRANCH on attempt $attempt"
            exit 0
          else
            EXIT_CODE=$?
            echo "[WARN] Push failed on attempt $attempt with exit code $EXIT_CODE"
            if [ "$attempt" -lt "$MAX_RETRIES" ]; then
              echo "[INFO] Waiting ${RETRY_DELAY}s before retry..."
              sleep "$RETRY_DELAY"
            fi
          fi
        done

        echo "[ERROR] Failed to push branch after $MAX_RETRIES attempts" >&2
        exit 1
