name: Tag main and push tag
description: Fetch main, checkout, create tag, push tag with retry and validation
inputs:
  token:
    description: GitHub token (PAT)
    required: true
  tag:
    description: Tag name (vX.Y.Z format)
    required: true
outputs:
  commit:
    description: Commit hash of tagged main
    value: ${{ steps.tag.outputs.commit }}
runs:
  using: composite
  steps:
    - name: Pre-check - validate tag format
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
      run: |
        set -euo pipefail
        if ! echo "$TAG" | grep -Eqx 'v[0-9]+\.[0-9]+\.[0-9]+'; then
          echo "ERROR: Invalid tag format (expected vX.Y.Z): $TAG" >&2
          exit 1
        fi
        echo "[INFO] Tag format validated: $TAG"

    - name: Fetch main and tags
      shell: bash
      env:
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
      run: |
        set -euo pipefail
        echo "[INFO] Fetching main branch..."
        git fetch origin main --force
        echo "[INFO] Fetching all tags..."
        git fetch --tags --force
        echo "[INFO] Checking out main..."
        git checkout -B main origin/main
        echo "[INFO] Current HEAD:"
        git log -1 --format=%H%n%s
        
    - name: Check tag doesn't already exist
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
      run: |
        set -euo pipefail
        if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
          echo "ERROR: Tag already exists: $TAG" >&2
          git tag -l "$TAG" -n1
          exit 1
        fi
        echo "[INFO] Tag does not exist: $TAG"

    - name: Create and push tag with retry
      id: tag
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        TAG: ${{ inputs.tag }}
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
      run: |
        set -euo pipefail

        COMMIT=$(git rev-parse HEAD)
        echo "[INFO] Tagging commit: $COMMIT"

        git tag "$TAG"
        echo "[INFO] Created tag: $TAG"
        git tag -l "$TAG" -n1

        git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git remote -v

        MAX_RETRIES=3
        RETRY_DELAY=2
        attempt=0

        while [ "$attempt" -lt "$MAX_RETRIES" ]; do
          attempt=$((attempt + 1))
          echo "[INFO] Push tag attempt $attempt/$MAX_RETRIES"

          if git push origin "$TAG" --no-verify; then
            echo "[INFO] Successfully pushed tag $TAG on attempt $attempt"
            echo "commit=$COMMIT" >> "$GITHUB_OUTPUT"
            exit 0
          else
            EXIT_CODE=$?
            echo "[WARN] Tag push failed on attempt $attempt with exit code $EXIT_CODE"
            if [ "$attempt" -lt "$MAX_RETRIES" ]; then
              echo "[INFO] Waiting ${RETRY_DELAY}s before retry..."
              sleep "$RETRY_DELAY"
            fi
          fi
        done

        echo "[ERROR] Failed to push tag after $MAX_RETRIES attempts" >&2
        git tag --delete "$TAG"
        echo "[INFO] Cleaned up local tag: $TAG"
        exit 1
