# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: gh pr merge
description: Merge a pull request via GitHub CLI
inputs:
  token:
    description: GitHub token for gh
    required: true
  pr_number:
    description: Pull request number
    required: true
  method:
    description: Merge method (merge|squash|rebase)
    required: false
    default: squash
  delete_branch:
    description: Delete branch after merge (true|false)
    required: false
    default: "true"
  admin:
    description: Use --admin (true|false)
    required: false
    default: "false"
  subject:
    description: Commit subject
    required: false
    default: ""
  body:
    description: Commit body
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Merge PR
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        PR: ${{ inputs.pr_number }}
        METHOD: ${{ inputs.method }}
        DELETE_BRANCH: ${{ inputs.delete_branch }}
        ADMIN: ${{ inputs.admin }}
        SUBJECT: ${{ inputs.subject }}
        BODY: ${{ inputs.body }}
      run: |
        set -euo pipefail

        args=("$PR" "--${METHOD}")

        if [ "$DELETE_BRANCH" = "true" ]; then
          args+=("--delete-branch")
        fi

        if [ "$ADMIN" = "true" ]; then
          args+=("--admin")
        fi

        if [ -n "${SUBJECT}" ]; then
          args+=("--subject" "$SUBJECT")
        fi

        # Allow empty body explicitly.
        args+=("--body" "$BODY")

        gh pr merge "${args[@]}"
